### ISSUE TITLE
catch Fact error concerning inconsistent ontology

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1581]
I want to prove anything in an inconsistent ontology:

```
logic OWL
ontology Inconsistency =
   Class: owl:Thing SubClassOf: 
                owl:Nothing 
   Class: A
   Class: B SubClassOf:  Annotations: Implied "true"^^xsd:string
                A

end
```

But then I get

```
Internal error.
FactProver: de.unibremen.informatik.FactProver.FactProver@7c2d0928

PhysicalIRI: file:///tmp/implied_Inconsistency_Ax211846.owl

GoalIRI: file:///tmp/implied_Inconsistency_Ax211846.owl.entail.owl

Inconsistent ontology
FaCT++.Kernel: Reasoner for the SROIQ(D) Description Logic, 64-bit
Copyright (C) Dmitry Tsarkov, 2002-2014. Version 1.6.3 (30 May 2014)
```

Instead, I would expect that the proof succeeds.

**Comment by tillmo** [comment]
The same holds for Pellet:
```
Exception in thread "main" org.mindswap.pellet.exceptions.InconsistentOntologyException: Cannot do reasoning with inconsistent ontologies!
Reason for inconsistency: There is an anonymous individual which is forced to belong to class _TOP_ and its complement
ExplanationSet: [subClassOf(owl:Thing, owl:Nothing)]
	at org.mindswap.pellet.KnowledgeBase.ensureConsistency(KnowledgeBase.java:2076)
	at org.mindswap.pellet.KnowledgeBase.isSubClassOf(KnowledgeBase.java:2775)
	at com.clarkparsia.pellet.owlapiv3.EntailmentChecker.visit(EntailmentChecker.java:187)
	at uk.ac.manchester.cs.owl.owlapi.OWLSubClassOfAxiomImpl.accept(OWLSubClassOfAxiomImpl.java:152)
	at com.clarkparsia.pellet.owlapiv3.EntailmentChecker.isEntailed(EntailmentChecker.java:120)
	at com.clarkparsia.pellet.owlapiv3.EntailmentChecker.findNonEntailments(EntailmentChecker.java:162)
	at pellet.PelletEntailment.run(PelletEntailment.java:117)
	at pellet.Pellet.run(Pellet.java:105)
	at pellet.Pellet.main(Pellet.java:59)
```

**Comment by tillmo** [comment]
I think this is a design decision of these provers. Inconstent ontologies are considered to be an error. But for Hets, they should not. they should be just marked as being inconsistent. Therefore, Hets should just catch such prover errors.
